--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'weapon_constants'

C2SWeaponIncrLevel = __TObject:new{
  heroId,
  weaponId
}

function C2SWeaponIncrLevel:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRING then
        self.heroId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.weaponId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function C2SWeaponIncrLevel:write(oprot)
  oprot:writeStructBegin('C2SWeaponIncrLevel')
  if self.heroId then
    oprot:writeFieldBegin('heroId', TType.STRING, 1)
    oprot:writeString(self.heroId)
    oprot:writeFieldEnd()
  end
  if self.weaponId then
    oprot:writeFieldBegin('weaponId', TType.STRING, 2)
    oprot:writeString(self.weaponId)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

S2CWeaponIncrLevel = __TObject:new{
  hero,
  curGold,
  costItem
}

function S2CWeaponIncrLevel:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.hero = HeroDTO:new{}
        self.hero:read(iprot)
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.I32 then
        self.curGold = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.STRUCT then
        self.costItem = ItemDTO:new{}
        self.costItem:read(iprot)
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function S2CWeaponIncrLevel:write(oprot)
  oprot:writeStructBegin('S2CWeaponIncrLevel')
  if self.hero then
    oprot:writeFieldBegin('hero', TType.STRUCT, 1)
    self.hero:write(oprot)
    oprot:writeFieldEnd()
  end
  if self.curGold then
    oprot:writeFieldBegin('curGold', TType.I32, 2)
    oprot:writeI32(self.curGold)
    oprot:writeFieldEnd()
  end
  if self.costItem then
    oprot:writeFieldBegin('costItem', TType.STRUCT, 3)
    self.costItem:write(oprot)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

C2SWeaponIncrQuality = __TObject:new{
  heroId,
  weaponId
}

function C2SWeaponIncrQuality:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRING then
        self.heroId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.weaponId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function C2SWeaponIncrQuality:write(oprot)
  oprot:writeStructBegin('C2SWeaponIncrQuality')
  if self.heroId then
    oprot:writeFieldBegin('heroId', TType.STRING, 1)
    oprot:writeString(self.heroId)
    oprot:writeFieldEnd()
  end
  if self.weaponId then
    oprot:writeFieldBegin('weaponId', TType.STRING, 2)
    oprot:writeString(self.weaponId)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

S2CWeaponIncrQuality = __TObject:new{
  hero,
  curGold,
  cost
}

function S2CWeaponIncrQuality:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.hero = HeroDTO:new{}
        self.hero:read(iprot)
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.I32 then
        self.curGold = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.LIST then
        self.cost = {}
        local _etype3, _size0 = iprot:readListBegin()
        for _i=1,_size0 do
          local _elem4 = ItemDTO:new{}
          _elem4:read(iprot)
          table.insert(self.cost, _elem4)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function S2CWeaponIncrQuality:write(oprot)
  oprot:writeStructBegin('S2CWeaponIncrQuality')
  if self.hero then
    oprot:writeFieldBegin('hero', TType.STRUCT, 1)
    self.hero:write(oprot)
    oprot:writeFieldEnd()
  end
  if self.curGold then
    oprot:writeFieldBegin('curGold', TType.I32, 2)
    oprot:writeI32(self.curGold)
    oprot:writeFieldEnd()
  end
  if self.cost then
    oprot:writeFieldBegin('cost', TType.LIST, 3)
    oprot:writeListBegin(TType.STRUCT, #self.cost)
    for _,iter5 in ipairs(self.cost) do
      iter5:write(oprot)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

C2SWeaponOneKeyIncrLvl = __TObject:new{
  heroId,
  weaponId,
  lvl
}

function C2SWeaponOneKeyIncrLvl:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRING then
        self.heroId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.weaponId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.I32 then
        self.lvl = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function C2SWeaponOneKeyIncrLvl:write(oprot)
  oprot:writeStructBegin('C2SWeaponOneKeyIncrLvl')
  if self.heroId then
    oprot:writeFieldBegin('heroId', TType.STRING, 1)
    oprot:writeString(self.heroId)
    oprot:writeFieldEnd()
  end
  if self.weaponId then
    oprot:writeFieldBegin('weaponId', TType.STRING, 2)
    oprot:writeString(self.weaponId)
    oprot:writeFieldEnd()
  end
  if self.lvl then
    oprot:writeFieldBegin('lvl', TType.I32, 3)
    oprot:writeI32(self.lvl)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

S2CWeaponOneKeyIncrLvl = __TObject:new{
  hero,
  curGold,
  costItem
}

function S2CWeaponOneKeyIncrLvl:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.hero = HeroDTO:new{}
        self.hero:read(iprot)
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.I32 then
        self.curGold = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.STRUCT then
        self.costItem = ItemDTO:new{}
        self.costItem:read(iprot)
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function S2CWeaponOneKeyIncrLvl:write(oprot)
  oprot:writeStructBegin('S2CWeaponOneKeyIncrLvl')
  if self.hero then
    oprot:writeFieldBegin('hero', TType.STRUCT, 1)
    self.hero:write(oprot)
    oprot:writeFieldEnd()
  end
  if self.curGold then
    oprot:writeFieldBegin('curGold', TType.I32, 2)
    oprot:writeI32(self.curGold)
    oprot:writeFieldEnd()
  end
  if self.costItem then
    oprot:writeFieldBegin('costItem', TType.STRUCT, 3)
    self.costItem:write(oprot)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end