--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'astrology_constants'

C2SLightAstrology = __TObject:new{
  heroId,
  astrologyConfigId
}

function C2SLightAstrology:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRING then
        self.heroId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.astrologyConfigId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function C2SLightAstrology:write(oprot)
  oprot:writeStructBegin('C2SLightAstrology')
  if self.heroId then
    oprot:writeFieldBegin('heroId', TType.STRING, 1)
    oprot:writeString(self.heroId)
    oprot:writeFieldEnd()
  end
  if self.astrologyConfigId then
    oprot:writeFieldBegin('astrologyConfigId', TType.STRING, 2)
    oprot:writeString(self.astrologyConfigId)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

S2CLightAstrology = __TObject:new{
  costAstrologyItem,
  newAstrologyConfigId,
  heroID
}

function S2CLightAstrology:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.costAstrologyItem = ItemDTO:new{}
        self.costAstrologyItem:read(iprot)
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.newAstrologyConfigId = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.STRING then
        self.heroID = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function S2CLightAstrology:write(oprot)
  oprot:writeStructBegin('S2CLightAstrology')
  if self.costAstrologyItem then
    oprot:writeFieldBegin('costAstrologyItem', TType.STRUCT, 1)
    self.costAstrologyItem:write(oprot)
    oprot:writeFieldEnd()
  end
  if self.newAstrologyConfigId then
    oprot:writeFieldBegin('newAstrologyConfigId', TType.STRING, 2)
    oprot:writeString(self.newAstrologyConfigId)
    oprot:writeFieldEnd()
  end
  if self.heroID then
    oprot:writeFieldBegin('heroID', TType.STRING, 3)
    oprot:writeString(self.heroID)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end